### ISSUE TITLE
Connect to the cluster

### ISSUE THREAD

**Issue by ayenller** [tidbcloud/tidbcloud-cli#112]
**Describe the bug**
The document is wrong: 
https://docs.pingcap.com/tidbcloud/get-started-with-cli#connect-to-the-cluster
connect to the cluster command is wrong.

**Version (please complete the following information):**
 - CLI version
 % ticloud version
ticloud version 0.5.1 (build date: 2023-07-18T04:21:26Z commit: b4878c3)
https://github.com/tidbcloud/tidbcloud-cli/releases/tag/v0.5.1

 - OS version
% uname -a
Darwin MacBook-Pro.local 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103 arm64

**To Reproduce**
% ticloud cluster connect
Manage clusters for your project

Usage:
  ticloud cluster [command]

Available Commands:
  connect-info Get connection string for the specified cluster
  create       Create one cluster in the specified project
  delete       Delete a cluster from your project
  describe     Describe a cluster
  list         List all clusters in a project

Flags:
  -h, --help   help for cluster

Global Flags:
  -D, --debug            Enable debug mode
      --no-color         Disable color output
  -P, --profile string   Profile to use from your configuration file

Use "ticloud cluster [command] --help" for more information about a command.

**Expected behavior**
The command should connect to serverless cluster, but not.
When use "ticloud connect" command, the result is expected.

**Comment by xuanyu66** [comment]
The doc is incorrect. We will fix it soon.

**Comment by xuanyu66** [comment]
@ayenller The doc has been fixed.
